# 1. 환경 설정

In [1]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

In [2]:
def setup_data():
    org_path = "C:/Users/Owner/Desktop/지윤/3.기타/프로젝트/purchase-conversion-prediction/"
    raw_path = f"{org_path}data/raw/"
    prc_path = f"{org_path}data/processed/"
    seed = 42

    print("변수 세팅 완료")
    return org_path, raw_path, prc_path, seed

# 사용 예시 (반환값 9개)
org_path, raw_path, prc_path, seed = setup_data()

변수 세팅 완료

# 2. 테이블 로드

In [3]:
def load_multiple_csv(base_path: str, filenames: list[str]) -> dict[str, pd.DataFrame]:
    """
    여러 CSV 파일을 한 번에 불러와 DataFrame 딕셔너리로 반환합니다.
    
    Parameters
    ----------
    base_path : str
        기본 경로 (예: "data/raw/")
    filenames : list[str]
        확장자를 제외한 파일명 리스트 (예: ["orders", "products", "users"])

    Returns
    -------
    dict[str, pd.DataFrame]
        각 파일명을 key, DataFrame을 value로 하는 딕셔너리
    """
    base = Path(base_path)
    dataframes = {}

    for name in filenames:
        file_path = base / f"{name}.csv"
        if not file_path.exists():
            print(f"파일 없음: {file_path}")
            continue
        df = pd.read_csv(file_path)
        dataframes[name] = df
        print(f"{name}.csv 로드 완료. shape={df.shape}")

    return dataframes

In [4]:
file_list = [
    "distribution_centers", "events", "inventory_items",
    "order_items", "orders", "products", "users"
]

# CSV 로드
dfs = load_multiple_csv(raw_path, file_list)

distribution_centers.csv 로드 완료. shape=(10, 4)
events.csv 로드 완료. shape=(2431963, 13)
inventory_items.csv 로드 완료. shape=(490705, 12)
order_items.csv 로드 완료. shape=(181759, 11)
orders.csv 로드 완료. shape=(125226, 9)
products.csv 로드 완료. shape=(29120, 9)
users.csv 로드 완료. shape=(100000, 15)

In [5]:
# 변수 자동 생성
for name, df in dfs.items():
    globals()[name] = df
    print(f"변수 생성 완료: {name} (shape={df.shape})")

변수 생성 완료: distribution_centers (shape=(10, 4))
변수 생성 완료: events (shape=(2431963, 13))
변수 생성 완료: inventory_items (shape=(490705, 12))
변수 생성 완료: order_items (shape=(181759, 11))
변수 생성 완료: orders (shape=(125226, 9))
변수 생성 완료: products (shape=(29120, 9))
변수 생성 완료: users (shape=(100000, 15))

# 3. 테이블별 요약 정보 확인

## 3.1 distribution_centers

In [6]:
# 1단계: 자동 추론
distribution_centers =  distribution_centers.convert_dtypes()

# 2단계: 중요한 컬럼만 명시적으로
force_dtypes = {
    'id': 'string'
}
distribution_centers = distribution_centers.astype({k: v for k, v in force_dtypes.items() if k in distribution_centers.columns})

In [7]:
distribution_centers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         10 non-null     string
 1   name       10 non-null     string
 2   latitude   10 non-null     Float64
 3   longitude  10 non-null     Float64
dtypes: Float64(2), string(2)
memory usage: 472.0 bytes

In [8]:
distribution_centers.describe(include='all')

         id        name   latitude  longitude
count    10          10       10.0       10.0
unique   10          10       <NA>       <NA>
top       1  Memphis TN       <NA>       <NA>
freq      1           1       <NA>       <NA>
mean    NaN         NaN   34.67931  -87.93855
std     NaN         NaN   4.572666  12.722916
min     NaN         NaN    29.7604    -118.25
25%     NaN         NaN  31.024975   -90.0428
50%     NaN         NaN   33.41665   -87.8639
75%     NaN         NaN   38.74185  -80.22915
max     NaN         NaN    41.8369   -73.7834

In [9]:
distribution_centers

   id                                         name  latitude  longitude
0   1                                   Memphis TN   35.1174   -89.9711
1   2                                   Chicago IL   41.8369   -87.6847
2   3                                   Houston TX   29.7604   -95.3698
3   4                               Los Angeles CA     34.05    -118.25
4   5                               New Orleans LA     29.95   -90.0667
5   6  Port Authority of New York/New Jersey NY/NJ    40.634   -73.7834
6   7                              Philadelphia PA     39.95   -75.1667
7   8                                    Mobile AL   30.6944   -88.0431
8   9                                Charleston SC   32.7833   -79.9333
9  10                                  Savannah GA   32.0167   -81.1167

## 3.1 events

In [10]:
# 데이터 타입 변환
# 1단계: 자동 추론
events =  events.convert_dtypes()

In [11]:
# 데이터 타입 변환
# 1단계: 자동 추론
events =  events.convert_dtypes()

# 2단계: 중요한 컬럼만 명시적으로
# 2단계: 중요한 컬럼만 명시적으로
force_dtypes = {
    'id': 'string',
    'user_id': 'string',
    'sequence_number': 'string',
}

events = events.astype({k: v for k, v in force_dtypes.items() if k in events.columns})

In [ ]:
cat_cols = events.select_dtypes(include=['string', 'category']).columns
key_cols = ['id', 'user_id', 'session_id', 'ip_address']
date_cols = ['created_at']

cat_cols = [col for col in cat_cols if col not in key_cols]
print("범주형 컬럼:", cat_cols)
print("키 컬럼:", key_cols)

범주형 컬럼: ['sequence_number', 'created_at', 'ip_address', 'city', 'state', 'postal_code', 'browser', 'traffic_source', 'uri', 'event_type']
키 컬럼: ['id', 'user_id', 'session_id']

### 데이터 전체 구조

In [14]:
events.describe(include='all')

,id,user_id,sequence_number,session_id,created_at,ip_address,city,state,postal_code,browser,traffic_source,uri,event_type
count,2431963,1306292,2431963,2431963,2431963,2431963,2408883,2431963,2431963,2431963,2431963,2431963,2431963
unique,2431963,80044,13,681759,2143390,681683,8775,231,17324,5,5,35530,6
top,844526,32996,1,e846b988-9b63-4997-8a85-a4b81318ad0f,2021-10-27 03:05:00+00:00,196.46.153.171,Shanghai,Guangdong,02675-031,Chrome,Email,/cart,product
freq,1,164,681759,13,8,17,60561,129796,10147,1218687,1091988,595994,845607

In [15]:
events.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2431963 entries, 0 to 2431962
Data columns (total 13 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   id               2431963 non-null  string
 1   user_id          1306292 non-null  string
 2   sequence_number  2431963 non-null  string
 3   session_id       2431963 non-null  string
 4   created_at       2431963 non-null  string
 5   ip_address       2431963 non-null  string
 6   city             2408883 non-null  string
 7   state            2431963 non-null  string
 8   postal_code      2431963 non-null  string
 9   browser          2431963 non-null  string
 10  traffic_source   2431963 non-null  string
 11  uri              2431963 non-null  string
 12  event_type       2431963 non-null  string
dtypes: string(13)
memory usage: 241.2 MB

In [16]:
events.head()

,id,user_id,sequence_number,session_id,created_at,ip_address,city,state,postal_code,browser,traffic_source,uri,event_type
0,2198523,<NA>,3,83889ed2-2adc-4b9a-af5d-154f6998e778,2021-06-17 17:30:00+00:00,138.143.9.202,São Paulo,São Paulo,02675-031,Chrome,Adwords,/cancel,cancel
1,1773216,<NA>,3,7a3fc3f2-e84f-44fe-8876-eff76741f7a3,2020-08-07 08:41:00+00:00,85.114.141.79,Santa Isabel,São Paulo,07500-000,Safari,Adwords,/cancel,cancel
2,2380515,<NA>,3,13d9b2fb-eee1-43fd-965c-267b38dd7125,2021-02-15 18:48:00+00:00,169.250.255.132,Mairiporã,São Paulo,07600-000,IE,Adwords,/cancel,cancel
3,2250597,<NA>,3,96f1d44e-9621-463c-954c-d8deb7fffe7f,2022-03-30 10:56:00+00:00,137.25.222.160,Cajamar,São Paulo,07750-000,Chrome,Adwords,/cancel,cancel
4,1834446,<NA>,3,d09dce10-a7cb-47d3-a9af-44975566fa03,2019-09-05 01:18:00+00:00,161.114.4.174,São Paulo,São Paulo,09581-680,Chrome,Email,/cancel,cancel

In [40]:
events['uri'].value_counts()

uri
/cart                                                                  595994
/purchase                                                              181759
/cancel                                                                125568
/home                                                                   87712
/department/women/category/maternity/brand/motherhoodmaternity           3354
                                                                        ...
/department/women/category/accessories/brand/allblack                       6
/department/women/category/fashionhoodies&sweatshirts/brand/citizen         6
/department/women/category/swim/brand/jamaicanstyle                         6
/department/men/category/outerwear&coats/brand/toesonthenose                5
/department/women/category/sweaters/brand/hotfromhollywood                  3
Name: count, Length: 35530, dtype: Int64

### 주요 변수 분포 및 특성 분석

In [38]:
def make_categorical_stats(df, cols, top_k=None, min_cnt=None):
    rows = []

    for c in cols:
        s = df[c].fillna("NA")
        vc = s.value_counts()

        if min_cnt is not None:
            vc = vc[vc >= min_cnt]
        if top_k is not None:
            vc = vc.head(top_k)
        if vc.empty:
            continue

        temp = vc.reset_index()
        temp.columns = ['key', 'cnt']          # 여기서 이름 강제
        temp['cnt'] = pd.to_numeric(temp['cnt'], errors='coerce')
        total = temp['cnt'].sum()

        temp['p'] = temp['cnt'] / total
        temp['col'] = c

        rows.append(temp)

    if not rows:
        return pd.DataFrame(columns=['col', 'key', 'cnt', 'p'])

    return pd.concat(rows, ignore_index=True)

In [39]:
make_categorical_stats(events, cat_cols)

                key     cnt         p              col
0                 1  681759  0.280333  sequence_number
1                 2  557043  0.229051  sequence_number
2                 3  432146  0.177694  sequence_number
3                 5  181759  0.074738  sequence_number
4                 4  181759  0.074738  sequence_number
...             ...     ...       ...              ...
2886958        cart  595994  0.245067       event_type
2886959  department  595323  0.244791       event_type
2886960    purchase  181759  0.074738       event_type
2886961      cancel  125568  0.051632       event_type
2886962        home   87712  0.036066       event_type

[2886963 rows x 4 columns]

In [ ]:
plot_categorical(events, 'city')

In [ ]:
analyze_categorical(events, cat_cols, top_n=5, bottom_n=5, value_head=20)

### sequence_number 생성 기준

In [ ]:
# 확인
events['sequence_number'].value_counts()

In [ ]:
# 같은 세션에서 여러 활동을 할 경우 sequence_number가 쌓이는 군
events.loc[events['sequence_number'] == 13, 'session_id'].value_counts().nunique()

In [ ]:
events.loc[events['sequence_number'] == 13, 'session_id'].head(1)

In [ ]:
session_value = events.loc[events["sequence_number"] == 13, "session_id"].iloc[0]
session_value

In [ ]:
events[events['session_id'] == session_value].sort_values('sequence_number')

In [ ]:
events.groupby('user_id').apply(lambda x: x['session_id'].nunique()).sort_values(ascending=False).head(10)
#[['user_id', 'session_id']]

In [ ]:
events[events['user_id'] == 32996.0].sort_values(['session_id', 'sequence_number'])

In [ ]:
# 사이트에 접속한 여러 유저들이 동일한 IP주소를 사용하는 경우가 있는가?
events.groupby(['ip_address'])['user_id'].nunique().value_counts()

In [ ]:
# 로그인한 세션 수 vs 비로그인 세션 수
# 비로그인 세션이 압도적으로 많음
events.groupby('session_id')['user_id'].nunique().value_counts()

In [ ]:
events.shape

In [ ]:
# created_at이 문자열이면 datetime으로 변환
events["created_at"] = pd.to_datetime(events["created_at"], utc=True, errors="coerce")

#세션 간 간격(= 발생 시간 간격)
session_duration = (
    events.groupby("session_id")["created_at"]
    .agg(session_start="min", session_end="max")
    .assign(session_duration=lambda x: (x["session_end"] - x["session_start"]).dt.total_seconds() / 60) # 분 단위로 확인
)

session_duration['session_duration'].describe()
# 생각보다 너무 긴데? 무슨 로그아웃하기 전까지 세션 안없어지는건가;;

In [ ]:
events['browser'].value_counts()

In [ ]:
events['traffic_source'].value_counts()

In [ ]:
events.loc[events['browser'] == 'Chrome', 'traffic_source'].value_counts()

In [ ]:
events.loc[events['browser'] == 'Other', 'traffic_source'].value_counts()

In [ ]:
# 아하 페이지 구경한거였구나? 그런 로그 기록이 다 담긴게 이벤트 테이블이군...
events['uri'].value_counts()

In [ ]:
# 
print(f'min: {events['created_at'].min()}')
print(f'max: {events['created_at'].max()}')

## 3.1 inventory_items

In [ ]:
inventory_items.info(show_counts=True)

In [ ]:
inventory_items.describe(include='all')

In [ ]:
inventory_items

In [ ]:
print(inventory_items['id'].nunique())
print(inventory_items['product_id'].nunique())
print(inventory_items['product_sku'].nunique())

In [ ]:
inventory_items['product_distribution_center_id'].value_counts()

In [ ]:
print(inventory_items['created_at'].min())
print(inventory_items['created_at'].max())

In [ ]:
print(inventory_items.loc[inventory_items['sold_at'].notnull(), 'sold_at'].min())
print(inventory_items.loc[inventory_items['sold_at'].notnull(), 'sold_at'].max())

In [ ]:
# datetime 변환
inventory_items["created_at"] = pd.to_datetime(inventory_items["created_at"], utc=True, errors="coerce")
inventory_items["sold_at"] = pd.to_datetime(inventory_items["sold_at"], utc=True, errors="coerce")

In [ ]:
# 재고 머무른 시간(미판매의 경우 비교적 최근 시점_sold_at최대값을 기준으로

# datetime 변환
inventory_items["created_at"] = pd.to_datetime(inventory_items["created_at"], utc=True, errors="coerce")
inventory_items["sold_at"] = pd.to_datetime(inventory_items["sold_at"], utc=True, errors="coerce")

# 기준일: sold_at의 최대값
reference_date = inventory_items["sold_at"].max()

# 판매된 상품 → 판매까지 걸린 기간
inventory_items["days_to_sell"] = (inventory_items["sold_at"] - inventory_items["created_at"]).dt.total_seconds() / 86400

# 미판매 상품 → 현재까지 재고로 남아 있는 기간
inventory_items.loc[inventory_items["sold_at"].isna(), "days_to_sell"] = (
    (reference_date - inventory_items["created_at"]).dt.total_seconds() / 86400
)

inventory_items["days_to_sell"] = inventory_items["days_to_sell"].round(1)

In [ ]:
inventory_items["days_to_sell"].describe()

## 3.1 order_items

In [ ]:
order_items.info(show_counts=True)

In [ ]:
order_items.describe(include='all')

In [ ]:
order_items

In [ ]:
print(order_items['id'].nunique())
print(order_items['order_id'].nunique())
print(order_items['user_id'].nunique())
print(order_items['product_id'].nunique())
print(order_items['inventory_item_id'].nunique())

In [ ]:
order_summary = (
    order_items
    .groupby("order_id")
    .agg(
        product_count=("product_id", "nunique"),   # 상품 종류 수
        status_count=("status", "nunique")         # 상태 종류 수
    )
    .reset_index()
)

In [ ]:
order_summary['product_count'].value_counts()

In [ ]:
order_summary['status_count'].value_counts()

## 3.1 orders

In [ ]:
events.info(show_counts=True)

In [ ]:
events.describe(include='all')

In [ ]:
events

## 3.1 products

In [ ]:
events.info(show_counts=True)

In [ ]:
events.describe(include='all')

In [ ]:
events

## 3.1 users

In [ ]:
events.info(show_counts=True)

In [ ]:
events.describe(include='all')

In [ ]:
events

## 3.1 events

In [ ]:
events.info(show_counts=True)

In [ ]:
events.describe(include='all')

In [ ]:
events